### ISSUE TITLE
use .jsx file extension

### ISSUE THREAD

**Issue by trungpham** [instructure-react/react-menu#13]
For some reason, my project cannot import react-menu. 

It complains about:
```
/Users/trungpham/projects/edcast-ui/node_modules/react-menu/lib/components/Menu.js:139
    return (<div>
            ^
SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/trungpham/projects/edcast-ui/node_modules/react-menu/lib/index.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by trungpham** [comment]
merged already #14
