### ISSUE TITLE
package json "main": "./dist/react-menu", ?

### ISSUE THREAD

**Issue by rkoberg** [instructure-react/react-menu#29]
Shouldn't the package.json's main property be "main": "./dist/react-menu", ?

As it is, I get an error:
```
/Users/rkoberg/Sites/tp/node_modules/react-menu/lib/components/Menu.js:139
      <div
      ^

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
```

**Comment by rkoberg** [comment]
Actually, doing that also produces an error:
```
/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:354
var MenuTrigger = module.exports = React.createClass({displayName: 'exports',
                                        ^

TypeError: Cannot read property 'createClass' of undefined
    at Object.4.../mixins/buildClassName (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:354:41)
    at s (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:609)
    at /Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:660
    at Object.1.../helpers/injectCSS (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:7:19)
    at s (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:609)
    at /Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:660
    at Object.7../components/Menu (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:464:12)
    at s (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:609)
    at e (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:780)
    at /Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:798
    at a (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:147)
    at Object.<anonymous> (/Users/rkoberg/Sites/tp/node_modules/react-menu/dist/react-menu.js:1:345)
    at Module._compile (module.js:430:26)
```
